xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml etc/xdg/xfce4/xfconf/xfce-perchannel-xml
xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml etc/xdg/xfce4/xfconf/xfce-perchannel-xml
xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml etc/xdg/xfce4/xfconf/xfce-perchannel-xml
xfce4/xfconf/xfce-perchannel-xml/xsettings.xml etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml-isd

xfce4/kioskrc /etc/xdg/xfce4/kiosk

artwork/backgrounds/* usr/share/backgrounds
artwork/icons/* usr/share/icons

vnc/indigovnc.service /lib/systemd/system
vnc/passwd /usr/share/indigosky-dektop
vnc/xstartup /usr/share/indigosky-dektop

lightdm/lightdm-gtk-greeter.conf etc/lightdm/lightdm-gtk-greeter.conf-isd
