#!/bin/sh
set -e

__check_file_exits() {
	[ ! -f ${1} ] && { echo "file '${1}' not found"; exit 0; }
}

__check_file_exits("/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml-isd/xsettings.xml.orig")

cp /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml-isd/xsettings.xml.orig /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml

exit 0
